apiVersion : apps/v1
kind: Deployment
metadata:
  name: "atomaks-a9b8"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "atomaks-a9b8"
  template:
    metadata:
      labels:
        app: "atomaks-a9b8"
    spec:
      containers:
        - name: "atomaks-a9b8"
          image: "atomacrr.azurecr.io/atomaks"
          ports:
          - containerPort: 9095