apiVersion: v1
kind: Service
metadata:
    name: "atomaks-a9b8"
    labels:
        app: "atomaks-a9b8"
spec:
    type: LoadBalancer
    ports:
    - port: 9095
      targetPort: 9095
      protocol: TCP
      name: http
    selector:
        app: "atomaks-a9b8"