on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: atomacrr.azurecr.io
        username: ${{ secrets.acr_atomacrr_username }}
        password: ${{ secrets.acr_atomacrr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/server" -f  "server/Dockerfile" -t atomacrr.azurecr.io/atomaks:${{ github.sha }} --label dockerfile-path=server/Dockerfile
        docker push atomacrr.azurecr.io/atomaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_atomaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep atom_kvn | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace atom_kvn`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: atom_kvn
        container-registry-url: atomacrr.azurecr.io
        container-registry-username: ${{ secrets.acr_atomacrr_username }}
        container-registry-password: ${{ secrets.acr_atomacrr_password }}
        secret-name: atomaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: atom_kvn
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          atomacrr.azurecr.io/atomaks:${{ github.sha }}
        imagepullsecrets: |
          atomaksdockerauth
